# Generated by Django 3.1 on 2020-11-20 00:09

import BookStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(default=BookStore.models.generate_unique_key, max_length=10, unique=True),
        ),
    ]
