# Generated by Django 3.1 on 2020-11-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_auto_20201120_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_books',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_replies',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ordered_books',
            field=models.JSONField(default=[]),
        ),
    ]
