# Generated by Django 3.1 on 2020-11-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_comments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
    ]
